<?php
/**
 * Created by PhpStorm.
 * User: joakim
 * Date: 22/08/16
 * Time: 22:51
 */

namespace Vinnia\Upsales\Test;

use Codeception\TestCase\Test;
use Vinnia\Upsales\Client;

class ClientTest extends Test
{

    private $env;

    /**
     * @var Client
     */
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->env = require __DIR__.'/../../env.php';
        $this->client = Client::make($this->env['accessToken']);
    }

    /** @test */
    public function it_should_load_1000_clients()
    {
        $res = $this->client->getClients();
        $clients = Client::decodeResponse($res);

        codecept_debug($clients);
        $this->assertEquals(1000,count($clients['data']));
    }

    /**
     * @test
     */
    public function it_should_find_vinnia_by_orgnr()
    {
        $res = $this->client->getClientByOrgNo('556933-9251');
        $clients = Client::decodeResponse($res);
        codecept_debug($clients);
        $this->assertEquals(1, count($clients['metadata']['total']));
    }
}