<?php
/**
 * Created by PhpStorm.
 * User: johan
 * Date: 2016-09-22
 * Time: 17:41
 */

namespace Vinnia\Upsales\Test;


use Codeception\TestCase\Test;
use Vinnia\Upsales\Validator;

class ValidatorTest extends Test
{

    /**
     * @var Validator
     */
    public $validator;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->validator = Validator::make();
    }

    public function testValidateOrder()
    {
        $data = [
            'description' => 'Harambe',
            'date' => '2016-09-22T17:50:00+02:00',
            'user' => 1,
            'stage' => 2,
            'probability' => 3,
            'client' => 4,
            'orderRow' => [
                [
                    'product' => [
                        'id' => 5,
                    ],
                    'price' => 6,
                    'quantity' => 7,
                ],
                [
                    'product' => [
                        'id' => 8,
                    ],
                    'price' => 9,
                    'quantity' => 10,
                ],
            ],
        ];

        $res = $this->validator->validateOrder($data);
        codecept_debug((string) $res);
        $this->assertCount(0, $res);

        $data['orderRow'][0]['product']['id'] = 'Hello World';

        $res = $this->validator->validateOrder($data);
        codecept_debug((string) $res);
        $this->assertCount(1, $res);
    }

}
